name       : libjpeg-turbo
version    : 2.0.1
release    : 11
source     :
    - https://kent.dl.sourceforge.net/project/libjpeg-turbo/2.0.1/libjpeg-turbo-2.0.1.tar.gz : e5f86cec31df1d39596e0cca619ab1b01f99025a27dafdfc97a30f3a12f866ff
homepage   : https://libjpeg-turbo.org/
component  : desktop.library
license    :
    - BSD-3-Clause
    - IJG
    - Zlib
optimize   : speed
emul32     : yes
summary    : libjpeg-turbo is a a fork of the original IJG libjpeg, offering faster compression and decompression.
description: |
    libjpeg-turbo is a fork of the original IJG libjpeg which uses SIMD to accelerate baseline JPEG compression and decompression. libjpeg is a library that implements JPEG image encoding, decoding and transcoding.
patterns   :
    - devel : /usr/bin
    - docs : [/usr/share/doc, /usr/share/man]
setup      : |
    %cmake_ninja -DCMAKE_INSTALL_DEFAULT_LIBDIR=lib%LIBSUFFIX% \
                -DENABLE_STATIC=FALSE \
                -DWITH_JPEG8=TRUE
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
