name       : libjpeg-turbo
version    : 1.5.3
release    : 8
source     :
    - https://kent.dl.sourceforge.net/project/libjpeg-turbo/1.5.3/libjpeg-turbo-1.5.3.tar.gz : b24890e2bb46e12e72a79f7e965f409f4e16466d00e1dd15d93d73ee6b592523
homepage   : https://libjpeg-turbo.org/
component  : desktop.library
license    :
    - BSD-3-Clause
    - IJG
    - Zlib
optimize   : speed
emul32     : yes
summary    : libjpeg-turbo is a a fork of the original IJG libjpeg, offering faster compression and decompression.
description: |
    libjpeg-turbo is a fork of the original IJG libjpeg which uses SIMD to accelerate baseline JPEG compression and decompression. libjpeg is a library that implements JPEG image encoding, decoding and transcoding.
patterns   :
    - devel : /usr/bin
    - docs : [/usr/share/doc, /usr/share/man]
setup      : |
    %configure --disable-static \
        --with-jpeg8
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
