name        : libjpeg-turbo
version     : 1.4.0
release     : 5
source      :
    - http://downloads.sourceforge.net/libjpeg-turbo/libjpeg-turbo-1.4.0.tar.gz : d93ad8546b510244f863b39b4c0da0fa4c0d53a77b61a8a3880f258c232bbbee
homepage    : http://sourceforge.net/projects/libjpeg-turbo/
license     :
    - BSD
summary     : libjpeg-turbo is a a fork of the original IJG libjpeg, offering faster compression and decompression.
builddeps   :
    - nasm
optimize    : speed
patterns:
    - devel: /usr/bin
    - docs: [/usr/share/doc, /usr/share/man]
description : |
    libjpeg-turbo is a fork of the original IJG libjpeg which uses SIMD to accelerate baseline JPEG compression and decompression. libjpeg is a library that implements JPEG image encoding, decoding and transcoding.
setup      : |
    ./configure --prefix=/usr \
                --mandir=/usr/share/man \
                --with-jpeg8 \
                --disable-static
build      : |
    %make
install    : |
    %make_install docdir=/usr/share/doc/libjpeg-turbo exampledir=/usr/share/doc/libjpeg-turbo
