name       : libjpeg-turbo
version    : 2.1.0
release    : 16
source     :
    - https://github.com/libjpeg-turbo/libjpeg-turbo/archive/refs/tags/2.1.0.tar.gz : d6b7790927d658108dfd3bee2f0c66a2924c51ee7f9dc930f62c452f4a638c52
homepage   : https://libjpeg-turbo.org/
component  : desktop.library
license    :
    - BSD-3-Clause
    - IJG
    - Zlib
optimize   :
    - speed
    - lto
emul32     : yes
summary    : libjpeg-turbo is a a fork of the original IJG libjpeg, offering faster compression and decompression.
description: |
    libjpeg-turbo is a fork of the original IJG libjpeg which uses SIMD to accelerate baseline JPEG compression and decompression. libjpeg is a library that implements JPEG image encoding, decoding and transcoding.
patterns   :
    - devel : /usr/bin
    - docs : [/usr/share/doc, /usr/share/man]
setup      : |
    %cmake_ninja -DCMAKE_INSTALL_DEFAULT_LIBDIR=lib%LIBSUFFIX% \
                -DENABLE_STATIC=FALSE \
                -DWITH_JPEG8=TRUE
build      : |
    %ninja_build
profile    : |
    # Running the testsuite helps decreases the solib size
    %ninja_check
    # Tjbench improves throughput
    pushd solusBuildDir
    ./tjbench ../testimages/testimgari.jpg
    ./tjbench ../testimages/testimgint.jpg
    ./tjbench ../testimages/testorig12.jpg
    popd
install    : |
    %ninja_install
check      : |
    %ninja_check
